# Generated by Django 4.1.10 on 2024-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusers",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
