# Generated by Django 4.1.10 on 2024-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
