# Generated by Django 4.1.10 on 2024-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="bots_info",
            field=models.JSONField(default=list),
        ),
    ]
