# Generated by Django 4.1.10 on 2025-02-12 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_delete_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="difficulty",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
